# .github/workflows/build.yml (on main branch)
name: Build from main

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the name of the branch to checkout'
        required: true
        default: 'main'
        type: string 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Run your code
        run: |
          echo "Running code of your provided branch: ${{ inputs.branch_name }}"
          echo "${cat index.html}"
