name: Branch testing Action

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "This is dev Branch (hard coded) !"
          echo "This is  ${GITHUB_REF##*/} Branch (variable used) !"
      - name: Step 2 updated
        run: |
          echo "This is dev Branch (hard coded) !"
          echo "This is  ${GITHUB_REF##*/} Branch (variable used) !"          
