name: Secret action

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Secret step 1
        run: |
          echo "This is Devops Branch (hard coded) !"
          echo "This is  ${GITHUB_REF##*/} Branch (variable used) !"
      - name: Secret step 2
        run: |
          echo "This is Devops Branch (hard coded) !"
          echo "This is  ${GITHUB_REF##*/} Branch (variable used) !"          
